apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-node
spec:
  selector:
    matchLabels:
      app: api-node
  template:
    metadata:
      labels:
        app: api-node
    spec:
      containers:
      - name: api-node
        image: node-api-docker
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8080"
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          protocol: TCP
          name: tcp
          
---
apiVersion: v1
kind: Service
metadata:
  name: api-node
spec:
  selector:
    app: api-node
  ports:
  - port: 80
    targetPort: 8080
    name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-node-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: api-node.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-node
            port:
              number: 80